/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_colorer_FileType */

#ifndef _Included_net_sf_colorer_FileType
#define _Included_net_sf_colorer_FileType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_colorer_FileType
 * Method:    getBaseScheme
 * Signature: (J)Lnet/sf/colorer/Scheme;
 */
JNIEXPORT jobject JNICALL Java_net_sf_colorer_FileType_getBaseScheme
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_colorer_FileType
 * Method:    enumerateParameters
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_colorer_FileType_enumerateParameters
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_sf_colorer_FileType
 * Method:    getParameterDescription
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_colorer_FileType_getParameterDescription
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_sf_colorer_FileType
 * Method:    getParamValue
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_colorer_FileType_getParamValue
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_sf_colorer_FileType
 * Method:    getParamDefaultValue
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_colorer_FileType_getParamDefaultValue
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_sf_colorer_FileType
 * Method:    setParamValue
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sf_colorer_FileType_setParamValue
  (JNIEnv *, jobject, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
