/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_colorer_Region */

#ifndef _Included_net_sf_colorer_Region
#define _Included_net_sf_colorer_Region
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
