/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_colorer_handlers_RegionMapper */

#ifndef _Included_net_sf_colorer_handlers_RegionMapper
#define _Included_net_sf_colorer_handlers_RegionMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_colorer_handlers_RegionMapper
 * Method:    finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_colorer_handlers_RegionMapper_finalize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_colorer_handlers_RegionMapper
 * Method:    getRegionDefine
 * Signature: (JLnet/sf/colorer/Region;)Lnet/sf/colorer/handlers/RegionDefine;
 */
JNIEXPORT jobject JNICALL Java_net_sf_colorer_handlers_RegionMapper_getRegionDefine__JLnet_sf_colorer_Region_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     net_sf_colorer_handlers_RegionMapper
 * Method:    getRegionDefine
 * Signature: (JLjava/lang/String;)Lnet/sf/colorer/handlers/RegionDefine;
 */
JNIEXPORT jobject JNICALL Java_net_sf_colorer_handlers_RegionMapper_getRegionDefine__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
